spring:
  application:
    name: Producer
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:postgres}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:Welcome123}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# spring:
#   application:
#     name: Producer
#   datasource:
#     url: jdbc:h2:mem:testdb
#     driverClassName: org.h2.Driver
#     username: sa
#     password:
#   jpa:
#     database-platform: org.hibernate.dialect.H2Dialect
#   h2:
#     console:
#       enabled: true
#       settings:
#         web-allow-others: true      

server:
  compression:
    enabled: true
    mime-types: application/json,application/javascript,application/xml,text/html,text/xml,text/plain
  servlet:
    context-path: /producer
  port: 8443